//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxiCall.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CulturedBot {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CulturedBot() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxiCall.Bot.Resources.CulturedBot", typeof(CulturedBot).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je n&apos;ai pas compris..
        /// </summary>
        public static string AdmitNotUnderstanding {
            get {
                return ResourceManager.GetString("AdmitNotUnderstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle est le nom de la compagnie concernée pour cette demande?.
        /// </summary>
        public static string AskCompanyName {
            get {
                return ResourceManager.GetString("AskCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quelle date estimez-vous pouvoir conclure cette opportunité?.
        /// </summary>
        public static string AskEstimatedClosingDateOfOpportunity {
            get {
                return ResourceManager.GetString("AskEstimatedClosingDateOfOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avez-vous un commentaire a ajouté?.
        /// </summary>
        public static string AskForComment {
            get {
                return ResourceManager.GetString("AskForComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que puis-je faire pour vous?.
        /// </summary>
        public static string AskForRequest {
            get {
                return ResourceManager.GetString("AskForRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que puis-je faire pour vous à présent?.
        /// </summary>
        public static string AskForRequestAgain {
            get {
                return ResourceManager.GetString("AskForRequestAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour quel client désirez-vous créer cette opportunité?.
        /// </summary>
        public static string AskForWhichLeadToCreateOpportunity {
            get {
                return ResourceManager.GetString("AskForWhichLeadToCreateOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour quel produit?.
        /// </summary>
        public static string AskForWhichProduct {
            get {
                return ResourceManager.GetString("AskForWhichProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhaitez vous être mis en contact ?.
        /// </summary>
        public static string AskIfWantForwardCall {
            get {
                return ResourceManager.GetString("AskIfWantForwardCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhaitez-vous réessayer?.
        /// </summary>
        public static string AskIfWantRetry {
            get {
                return ResourceManager.GetString("AskIfWantRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous passer cette étape?.
        /// </summary>
        public static string AskIfWantToSkip {
            get {
                return ResourceManager.GetString("AskIfWantToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle est la personne que vous recherchez ?.
        /// </summary>
        public static string AskSearchedPersonFullName {
            get {
                return ResourceManager.GetString("AskSearchedPersonFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez répondre par &apos;Oui&apos; ou  &apos;Non&apos; pour confirmer..
        /// </summary>
        public static string AskYesOrNo {
            get {
                return ResourceManager.GetString("AskYesOrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;est pas un nom complet..
        /// </summary>
        public static string FullNameIncomplete {
            get {
                return ResourceManager.GetString("FullNameIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} travaille pour {1}..
        /// </summary>
        public static string GiveCompanyName {
            get {
                return ResourceManager.GetString("GiveCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre contact chez {0} est {1}..
        /// </summary>
        public static string GiveContactName {
            get {
                return ResourceManager.GetString("GiveContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adresse email est {1}..
        /// </summary>
        public static string GiveEmailAddress {
            get {
                return ResourceManager.GetString("GiveEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} habite au {1}..
        /// </summary>
        public static string GiveHomeAddress {
            get {
                return ResourceManager.GetString("GiveHomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez en ce moment {0} opportunités avec {1}..
        /// </summary>
        public static string GivenNumberOfOpportunities {
            get {
                return ResourceManager.GetString("GivenNumberOfOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez en ce moment {0} opportunités avec cette compagnie..
        /// </summary>
        public static string GivenNumberOfOpportunitiesByCompany {
            get {
                return ResourceManager.GetString("GivenNumberOfOpportunitiesByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numéro de téléphone est le {1}.
        /// </summary>
        public static string GivePhoneNumber {
            get {
                return ResourceManager.GetString("GivePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue chez ProxiCall {0}..
        /// </summary>
        public static string Greet {
            get {
                return ResourceManager.GetString("Greet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous transférons votre appel..
        /// </summary>
        public static string InformAboutForwardingCall {
            get {
                return ResourceManager.GetString("InformAboutForwardingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        public static string LinkWithAnd {
            get {
                return ResourceManager.GetString("LinkWithAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pour le produit {0}, créée le {1}.
        /// </summary>
        public static string ListOpportunities {
            get {
                return ResourceManager.GetString("ListOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avec {0} pour le produit {1}, créée le {2}.
        /// </summary>
        public static string ListOpportunitiesOfCompany {
            get {
                return ResourceManager.GetString("ListOpportunitiesOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proxicall-luis.
        /// </summary>
        public static string LuisAppName {
            get {
                return ResourceManager.GetString("LuisAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les données suivantes sont absentes de la base de données : {0}..
        /// </summary>
        public static string MissingDataForThisLead {
            get {
                return ResourceManager.GetString("MissingDataForThisLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;a pas été trouvé..
        /// </summary>
        public static string NamedObjectNotFound {
            get {
                return ResourceManager.GetString("NamedObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solé, vous n&apos;avez pas les droits d&apos;accès requis..
        /// </summary>
        public static string NoAccessException {
            get {
                return ResourceManager.GetString("NoAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ces informations ne sont malheureusement pas référencées..
        /// </summary>
        public static string NoDataFoundInDB {
            get {
                return ResourceManager.GetString("NoDataFoundInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je n&apos;ai pas compris ce que vous venez de dire..
        /// </summary>
        public static string NoIntentFound {
            get {
                return ResourceManager.GetString("NoIntentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a pas de personnes référencées pour cette entreprise.
        /// </summary>
        public static string NoPointOfContactFound {
            get {
                return ResourceManager.GetString("NoPointOfContactFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de téléphone de {0} n&apos;a pas été trouvé..
        /// </summary>
        public static string PhoneNumberNotFound {
            get {
                return ResourceManager.GetString("PhoneNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allez-y!.
        /// </summary>
        public static string SayGoAhead {
            get {
                return ResourceManager.GetString("SayGoAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il.
        /// </summary>
        public static string SayHe {
            get {
                return ResourceManager.GetString("SayHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elle.
        /// </summary>
        public static string SayHer {
            get {
                return ResourceManager.GetString("SayHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        public static string SayHerPossesive {
            get {
                return ResourceManager.GetString("SayHerPossesive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lui.
        /// </summary>
        public static string SayHim {
            get {
                return ResourceManager.GetString("SayHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        public static string SayHisPossesive {
            get {
                return ResourceManager.GetString("SayHisPossesive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Très bien, l&apos;opportunité a bien été créée..
        /// </summary>
        public static string SayOpportunityWasCreated {
            get {
                return ResourceManager.GetString("SayOpportunityWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elle.
        /// </summary>
        public static string SayShe {
            get {
                return ResourceManager.GetString("SayShe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette information n&apos;est malheureusement pas référencée..
        /// </summary>
        public static string ThisDataNotFoundInDB {
            get {
                return ResourceManager.GetString("ThisDataNotFoundInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oui.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
